name: Build container

on:
    workflow_dispatch:

jobs:
    build-container:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Github Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5.3.0
              with:
                  context: ./src
                  file: ./src/discord/Dockerfile
                  platforms: linux/amd64,linux/arm64/v8
                  push: true
                  tags: ghcr.io/wjcrumbleholme/quoteguesser:latest
